"""
YouTube Account Manager
========================
yt-dlp pakai Netscape cookie format (cookies.txt). User export cookie via
extension browser, lalu paste isinya ke endpoint /accounts.

Extension recommended:
  - "Get cookies.txt LOCALLY" (Chrome/Firefox)
  - Login youtube.com, klik extension, copy isi file.

Format Netscape:
# Netscape HTTP Cookie File
.youtube.com    TRUE    /    TRUE    1234567890    SAPISID    abc123...
.youtube.com    TRUE    /    TRUE    1234567890    HSID    ...
...

Yang penting punya cookies: SAPISID, HSID, SSID, APISID, SID (auth Google).
Login optional sebenarnya — yt-dlp bisa search/download tanpa login. Tapi
dengan cookies, kita dapat:
  - akses video age-restricted
  - rate limit lebih longgar
  - comments lebih lengkap (karena some are gated)
"""

import logging
from typing import Optional

import requests

from .base import BaseAccountManager

logger = logging.getLogger(__name__)


class YouTubeAccountManager(BaseAccountManager):
    
    PLATFORM = "youtube"
    
    REQUIRED_COOKIES = ('SAPISID', 'HSID', 'SSID')  # any one indicates login
    
    def _do_login(self, username: str, password: str, verification_code: Optional[str] = None) -> dict:
        """
        password berisi:
          - Netscape cookies.txt content (full file isi), ATAU
          - JSON dict {"SAPISID":"...","HSID":"...",...}
          - String "anonymous" untuk akun tanpa login (rate-limited).
        """
        raw = (password or '').strip()
        
        if raw.lower() == 'anonymous':
            # Pakai akun tanpa cookie — useful untuk YouTube karena banyak hal publik
            self._session_path(username).write_text('# anonymous\n')
            return {'session_type': 'anonymous'}
        
        if raw.startswith('{'):
            # JSON — convert ke Netscape format
            import json
            try:
                cookies = json.loads(raw)
            except Exception as e:
                raise Exception(f"Invalid JSON cookie: {e}")
            netscape = self._json_to_netscape(cookies)
            cookie_dict = cookies
        elif raw.startswith('# Netscape') or '\t' in raw:
            netscape = raw
            cookie_dict = self._netscape_to_dict(raw)
        else:
            raise Exception(
                "YouTube butuh cookies. Format yang diterima:\n"
                "1. Isi cookies.txt (Netscape format) — export via 'Get cookies.txt LOCALLY' extension\n"
                "2. JSON dict {\"SAPISID\":\"...\",\"HSID\":\"...\"}\n"
                "3. 'anonymous' untuk tanpa login (rate-limited)"
            )
        
        if not any(cookie_dict.get(k) for k in self.REQUIRED_COOKIES):
            logger.warning(f"[youtube] {username}: tidak ada cookie auth, treating sebagai anonymous")
        
        self._session_path(username).write_text(netscape)
        return {
            'session_type': 'cookies' if any(cookie_dict.get(k) for k in self.REQUIRED_COOKIES) else 'anonymous',
        }
    
    @staticmethod
    def _json_to_netscape(cookies: dict) -> str:
        lines = ['# Netscape HTTP Cookie File', '# Generated by slaytics-scraper', '']
        for name, value in cookies.items():
            # domain, hostonly, path, secure, expiry, name, value
            lines.append(f'.youtube.com\tTRUE\t/\tTRUE\t2147483647\t{name}\t{value}')
        return '\n'.join(lines) + '\n'
    
    @staticmethod
    def _netscape_to_dict(content: str) -> dict:
        out = {}
        for line in content.splitlines():
            if line.startswith('#') or not line.strip():
                continue
            parts = line.split('\t')
            if len(parts) >= 7:
                out[parts[5]] = parts[6]
        return out
    
    def get_cookies_path(self, username: str):
        path = self._session_path(username)
        if not path.exists():
            raise Exception(f"No YouTube session for {username}")
        return path
